# Nombre de la aplicación
spring.application.name=Asistencia

# Configuración de SQLite
spring.datasource.url=jdbc:sqlite:data/asistenciaorm.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialecto personalizado para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
